use_frameworks!

platform :ios, '9.0'

target 'GGXSwiftExtension_Example' do
  pod 'GGXSwiftExtension', :path => '../'

  target 'GGXSwiftExtension_ExampleTests' do
    inherit! :search_paths

    
  end
end
