use_frameworks!

platform :ios, '11.0'

target 'GGXSwiftExtension_Example' do
  pod 'GGXSwiftExtension', :path => '../'
  pod 'SmartCodable'
  target 'GGXSwiftExtension_ExampleTests' do
    inherit! :search_paths

    
  end
end
