use_frameworks!

platform :ios, '10.0'

target 'GGXSwiftExtension_Example' do
  pod 'GGXSwiftExtension', :path => '../'

  target 'GGXSwiftExtension_Tests' do
    inherit! :search_paths

    
  end
end
